---
version: 2
project_name: git-commit-template
builds:
  - main: ./cmd/git-commit-template
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - --yes
    artifacts: checksum
brews:
  - name: git-commit-template
    repository:
      owner: carhartl
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_PUBLISH_TOKEN }}"
